services:
  web:
    image: prkappreg.azurecr.io/prkapp/sampleapp:v1.0
    container_name: test_app_container
    ports:
      - 8080:80
    networks:
      - test_frontend_network

networks:
  test_frontend_network:
    name: test_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.50.0.0/16
          ip_range: 10.50.1.0/24